version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.5.3
        environment:
          - DATABASE_HOST: db
          - DATABASE_USERNAME: root
          - DATABASE_PASSWORD: root
          - DATABASE_NAME: slot_sns
          - BUNDLER_VERSION: 2.0.2
          - RAILS_ENV: 'test'
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_USER: develop
          - MYSQL_PASSWORD: develop
          - TZ: Asia/Tokyo
        name: db
    steps:
      - checkout
      - run:
          name: install bundles
          command: |
            gem install bundler -v 2.0.2
            bundle install
      - run:
          name: Create Database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run test codes with RSpec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

              bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
