version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.5.3
        environment:
          - DATABASE_HOST: db
          - DATABASE_USERNAME: root
          - DATABASE_PASSWORD: root
          - DATABASE_NAME: slot_sns
          - BUNDLER_VERSION: 2.0.2
          - RAILS_ENV: 'test'
    steps:
      - checkout
      - run: rspec
      
